{% set name = "camb" %}
{% set version = "1.5.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/cmbant/CAMB/archive/{{ version }}.tar.gz
  sha256: 0ddc55159d9c32c1c7015f6c6af71a097eccd6e13a363acd4ba47f1de2f2077d
  patches:
    - makefile_flags_0001.patch  # [unix]

build:
  number: 0
  skip: true  # [py2k]
  script:                                                                                                   # [win]
    - {{ PYTHON }} -m pip install camb=={{ version }} -v --no-deps --no-build-isolation --ignore-installed  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('fortran') }}
    - git  # [not win]
    - m2-git  # [win]
    - make  # [not win]
    - m2-make  # [win]
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
    - setuptools
    - packaging
  run:
    - python
    - numpy
    - packaging
    - setuptools
    - sympy >=1.0
    - scipy >=1.0
    - {{ compiler('fortran') }}

test:
  imports:
    - camb
  files:
    - params.ini
    - test_pycamb.py
    - run_test.sh  # [win]

about:
  home: https://camb.info/
  license: modified LGPL
  license_family: LGPL
  license_file: {{ RECIPE_DIR }}/LICENSE
  summary: Code for Anisotropies in the Microwave Background
  description: |
    Code for Anisotropies in the Microwave Background
    by Antony Lewis and Anthony Challinor

    Features:
      - Support for closed, open and flat models
      - Scalar, vector and tensor modes including polarization
      - Output Cl, matter transfer functions, matter power spectrum and Ïƒ8
      - Fast computation to ~0.3-0.1% accuracy, with controllable accuracy level
      - Relatively structured and easily extendable Fortran 90 code
      - Efficient support for massive neutrinos
      - Absolute computations from correctly normalized initial power spectra
      - Computation of lensed CMB power spectra and lensing potential power spectrum
      - Internally parallelized for fast execution on multi-processor machines
      - Use CAMB with CosmoMC for Monte-Carlo parameter estimation
      - Constant equation of state quintessence (or variable PPF)
      - Support for general correlated adiabatic/isocurvature initial conditions
      - Accurate full-sky calculation of lensed power spectra (astro-ph/0502425)
      - Integrated interface to HALOFIT for non-linear fitting
      - support for arbitrary neutrino mass splittings
      - For 21cm, lensing and number count power spectra see this extension
      - For perturbed recombination and effect on small-scale baryons see this extension
      - Calculation of local primordial and CMB lensing bispectra
      - Easy-to-use Python wrapper
  doc_url: https://camb.info/readme.html
  dev_url: https://github.com/cmbant/CAMB

extra:
  recipe-maintainers:
    - beckermr
    - cmbant
