schema_version: 1

context:
  name: camb
  version: "2.0.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  - if: unix
    then:
      url: https://github.com/cmbant/CAMB/archive/${{ version }}.tar.gz
      sha256: ab72e80729cdba2907b243ba6680c3d67f2d21aeb279ccefe81089f75501904f
      patches:
        - makefile_flags_0001.patch
  - if: win
    then:
      url: https://camb.info/camb_wheel.php?package=camb&version=${{ version }}&template=py3-none-win_amd64
      sha256: 548167e87319163c334de661a8a86d3d2a482b9ae105090f79c23d3d74425573

build:
  number: 1
  skip: match(python, "<3.11")
  script:
    - if: win
      then:
        - ren camb_wheel.php camb-${{ version }}-py3-none-win_amd64.whl
        - ${{ PYTHON }} -m pip install camb-${{ version }}-py3-none-win_amd64.whl -vvv --no-deps --no-build-isolation --ignore-installed
      else:
        - build.sh

requirements:
  build:
    - if: not win
      then: ${{ compiler('c') }}
    - if: not win
      then: ${{ stdlib("c") }}
    - if: not win
      then: ${{ compiler('fortran') }}
    - if: not win
      then: git
    - if: not win
      then: make
    - if: build_platform != target_platform
      then: python
    - if: build_platform != target_platform
      then: cross-python_${{ target_platform }}
  host:
    - python
    - pip
    - setuptools
    - packaging
    - if: unix
      then:
        - if: linux
          then: libgomp
          else: llvm-openmp
  run:
    - python
    - numpy
    - packaging
    - setuptools
    - sympy >=1.0
    - scipy >=1.0
    - if: not win
      then: ${{ compiler('fortran') }}

tests:
  - python:
      imports:
        - camb
      pip_check: false
  - script:
      - if: win
        then: run_test.bat
        else: run_test.sh
    files:
      recipe:
        - params.ini
        - test_pycamb.py
        - run_test.sh
        - run_test.bat

about:
  license: LicenseRef-modified-LGPL
  license_file: LICENSE
  summary: Code for Anisotropies in the Microwave Background
  description: |
    CAMB is a cosmology code for calculating cosmological observables, including CMB,
    lensing, source count and 21cm angular power spectra, matter power spectra,
    transfer functions and background evolution, by Antony Lewis and Anthony Challinor.
    The code is in Python, with numerical code implemented in fast modern Fortran.

    See the CAMB python example notebook for a quick introduction to how to use the
    CAMB Python package: https://camb.readthedocs.io/en/latest/CAMBdemo.html

    The python module is "camb". Full documentation: https://camb.readthedocs.io/en/latest/
  homepage: https://camb.info/
  repository: https://github.com/cmbant/CAMB
  documentation: https://camb.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - beckermr
    - cmbant
