appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: abDiCQXxCxxDpBrsl9gTcv4mKoZW+aWxdfo+XCrSzfehmv7gJvfeUV16ids4SmP3iXKTTh2m57N9HePS+YdLUkgGt+z9GfJRxtpFNTPpY1qJN/N/adqLL0zYrvRzH13AFJCzNuHB+atJazzaMX5dPZA63yk5yspoHT72t38RsQ8vQZ2mZDG8VF7KZciWpz4zcSb4nlAWd8gEUm1Ch1K5eB8iF+Q9TJntEjev6kMU5+St6AivWtJeYkRNm5hf5cRhARZkH6DGhDbmJzPkATwbXlBuBUT67VfPZphUVZGGjVyYjIKarIzz0NrCRVJBiB2oH6DHy7lziq6XlP68OnKq8bBQy3p1iTF79VjaoHKbGcw95r6L5N0XMP0TByvRtUypVPSJ0vzdwGQKceowZjwhSv5ZXdFBqC7gn1jSJNxBa/zr/ImsF96A9vQCV+tpUEzxlUkt9gQp1hOlz5qIFVz9Fx3BiNvKuaDcRv6pZ8wfLDZgYS+CD5/tqlSyecWn2/sjpMy0HJWnFheuS+zyDxLb9VplqvW4qs69P8eI6hMxLEtL5gl38qyaLp6nJ1oDeW1Blj8bAgyQaXrEapuYIIZIzNIiXS41QtfN6/JP+TOjCl/lRt1mZo35HGH/C+C372/n5gRVmf842CGvOKcHPLOcjl01GUZbAA+Eom2luCRxgmI=}
provider:
  win: azure
bot:
  automerge: true
